# Generated by Django 4.1.7 on 2023-07-10 06:23

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_remove_profile_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="civil_status",
            field=models.CharField(
                choices=[
                    ("S", "Single"),
                    ("M", "Married"),
                    ("W", "Widowed"),
                    ("D", "Divorced"),
                ],
                default="Single",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="Philippines",
                max_length=50

            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="Others",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_cuisine",
            field=models.CharField(
                choices=[("1", "Italian"), ("2", "Mexican"), ("3", "Indian")],
                default="None",
                max_length=50,
            ),
        ),
    ]
