# Generated by Django 4.1.7 on 2023-07-10 06:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_profile_age_profile_birthday_profile_civil_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="civil_status",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Widowed", "Widowed"),
                    ("Divorced", "Divorced"),
                ],
                default="Single",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(default="PH", max_length=2),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Others", "Others")],
                default="Others",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preferred_cuisine",
            field=models.CharField(
                choices=[("1", "Italian"), ("2", "Mexican"), ("3", "Indian")],
                default="None",
                max_length=20,
            ),
        ),
    ]
