# Generated by Django 4.1.7 on 2023-07-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_alter_profile_civil_status_alter_profile_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="preferred_cuisine",
            field=models.CharField(
                choices=[
                    ("american", "American"),
                    ("caribbean", "Caribbean"),
                    ("chinese", "Chinese"),
                    ("european", "European"),
                    ("filipino", "Filipino"),
                    ("french", "French"),
                    ("german", "German"),
                    ("greek", "Greek"),
                    ("indonesian", "Indonesian"),
                    ("italian", "Italian"),
                    ("japanese", "Japanese"),
                    ("korean", "Korean"),
                    ("lebanese", "Lebanese"),
                    ("mexican", "Mexican"),
                    ("spanish", "Spanish"),
                    ("thai", "Thai"),
                    ("vietnamese", "Vietnamese"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
