# Generated by Django 5.1.6 on 2025-02-13 16:25

import django.db.models.deletion
import djrichtextfield.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('instructions', djrichtextfield.models.RichTextField(max_length=10000)),
                ('ingredients', djrichtextfield.models.RichTextField(max_length=10000)),
                ('preptime_hours', models.IntegerField(default=0)),
                ('preptime_minutes', models.IntegerField(default=0)),
                ('total_preptime', models.IntegerField(editable=False)),
                ('servings', models.IntegerField()),
                ('cooktime_hours', models.IntegerField(default=0)),
                ('cooktime_minutes', models.IntegerField(default=0)),
                ('total_cooktime', models.IntegerField(default=0, editable=False)),
                ('price', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('image_alt', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='breakfast', max_length=50)),
                ('recipe_difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=50)),
                ('cuisine_types', models.CharField(choices=[('american', 'American'), ('caribbean', 'Caribbean'), ('chinese', 'Chinese'), ('european', 'European'), ('filipino', 'Filipino'), ('french', 'French'), ('german', 'German'), ('greek', 'Greek'), ('indonesian', 'Indonesian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('lebanese', 'Lebanese'), ('mexican', 'Mexican'), ('spanish', 'Spanish'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese')], default='african', max_length=50)),
                ('calories', models.IntegerField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
