# Generated by Django 4.1.7 on 2023-07-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0014_recipe_rating_count_alter_recipe_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cuisine_types",
            field=models.CharField(
                choices=[
                    ("american", "American"),
                    ("caribbean", "Caribbean"),
                    ("chinese", "Chinese"),
                    ("european", "European"),
                    ("filipino", "Filipino"),
                    ("french", "French"),
                    ("german", "German"),
                    ("greek", "Greek"),
                    ("indonesian", "Indonesian"),
                    ("italian", "Italian"),
                    ("japanese", "Japanese"),
                    ("korean", "Korean"),
                    ("lebanese", "Lebanese"),
                    ("mexican", "Mexican"),
                    ("spanish", "Spanish"),
                    ("thai", "Thai"),
                    ("vietnamese", "Vietnamese"),
                ],
                default="african",
                max_length=50,
            ),
        ),
    ]
